

package ui.AdministrativeRole;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.logging.*;
/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    private final static Logger logr = Logger.getLogger(Logger.GLOBAL_LOGGER_NAME);
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        logr.info("LoggingIn");
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageuser = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        manageorganization = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        manageemployee = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 120, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, -1));

        manageuser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageuserMouseClicked(evt);
            }
        });

        jLabel3.setText("MANAGE USER");
        manageuser.add(jLabel3);

        add(manageuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 150, 120));

        manageorganization.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageorganization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageorganizationMouseClicked(evt);
            }
        });

        jLabel4.setText("MANAGE ORGANIZATION");
        manageorganization.add(jLabel4);

        add(manageorganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 150, 120));

        manageemployee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manageemployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageemployeeMouseClicked(evt);
            }
        });

        jLabel5.setText("MANAGE EMPLOYEE");
        manageemployee.add(jLabel5);

        add(manageemployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 150, 120));
    }// </editor-fold>//GEN-END:initComponents

    private void manageorganizationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageorganizationMouseClicked
 ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);  
        logr.info("Manage organization clicked");
    }//GEN-LAST:event_manageorganizationMouseClicked

    private void manageemployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageemployeeMouseClicked
ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);        
        logr.info("Manage Employess Clicked");
    }//GEN-LAST:event_manageemployeeMouseClicked

    private void manageuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageuserMouseClicked
 ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer); 
        logr.info("Manage User Clicked");
    }//GEN-LAST:event_manageuserMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel manageemployee;
    private javax.swing.JPanel manageorganization;
    private javax.swing.JPanel manageuser;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
